### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by thebabush** [thebabush/honggfuzz-qemu#1]
- [ ] static binaries don't work (probably due to code_start / code_end)
- [x] ~~figure out why code_end doesn't work as in AFL~~ I'm dumb, thanks to robertswiecki
- [ ] split 64-bit constants?
- [ ] better address hashing
- [ ] JIT the instrumentation
- [ ] re-enable tsl thing for caching to parent (this requires jitting the instrumentation or `QEMU_LOG=nochain`, the latter being slow)
- [ ] reimplement edge instrumentation in hfuzz's style (same caveats as above)
- [x] ~~fork-server (likely requires modification upstream)~~
- [ ] piggyback on AFLplusplus QEMU? Need to check the license.
